create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list Storage_i/zynq_ultra_ps_e_0/U0/pl_clk0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {Storage_i/axi_dma_0/m_axis_mm2s_tdata[0]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[1]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[2]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[3]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[4]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[5]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[6]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[7]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[8]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[9]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[10]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[11]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[12]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[13]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[14]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[15]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[16]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[17]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[18]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[19]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[20]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[21]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[22]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[23]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[24]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[25]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[26]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[27]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[28]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[29]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[30]} {Storage_i/axi_dma_0/m_axis_mm2s_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {Storage_i/axi_dma_0/s_axis_s2mm_tdata[0]} {Storage_i/axi_dma_0/s_axis_s2mm_tdata[1]} {Storage_i/axi_dma_0/s_axis_s2mm_tdata[2]} {Storage_i/axi_dma_0/s_axis_s2mm_tdata[3]} {Storage_i/axi_dma_0/s_axis_s2mm_tdata[4]} {Storage_i/axi_dma_0/s_axis_s2mm_tdata[5]} {Storage_i/axi_dma_0/s_axis_s2mm_tdata[6]} {Storage_i/axi_dma_0/s_axis_s2mm_tdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {Storage_i/FIFO_stream_0/M_AXIS_TDATA[0]} {Storage_i/FIFO_stream_0/M_AXIS_TDATA[1]} {Storage_i/FIFO_stream_0/M_AXIS_TDATA[2]} {Storage_i/FIFO_stream_0/M_AXIS_TDATA[3]} {Storage_i/FIFO_stream_0/M_AXIS_TDATA[4]} {Storage_i/FIFO_stream_0/M_AXIS_TDATA[5]} {Storage_i/FIFO_stream_0/M_AXIS_TDATA[6]} {Storage_i/FIFO_stream_0/M_AXIS_TDATA[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list Storage_i/FIFO_stream_0/M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list Storage_i/FIFO_stream_0/M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list Storage_i/FIFO_stream_0/M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list Storage_i/axi_dma_0/s_axis_s2mm_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list Storage_i/axi_dma_0/s_axis_s2mm_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list Storage_i/axi_dma_0/s_axis_s2mm_tvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_pl_clk0]
